# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('title', models.CharField(help_text='title', max_length=50, verbose_name='title')),
                ('author', models.CharField(help_text='name', max_length=50, verbose_name='name')),
                ('msg', models.TextField(help_text='Textual Notes', verbose_name='Textual Notes')),
            ],
        ),
    ]
